### ISSUE TITLE
d3.drag is not a function

### ISSUE THREAD

**Issue by gusevfe** [emepyc/tnt.tooltip#1]
Hello!

When trying to run example `simple` and click on the red circle the following error shows up in the console:

```
tooltip.js:6 Uncaught TypeError: d3.drag is not a function
    at tooltip (tooltip.js:6)
    at Function.tooltip.table (tooltip.js:176)
    at SVGCircleElement.t (index.html:20)
    at SVGCircleElement.__onclick (d3.v3.min.js:1)
```
Is there any workaround?

**Comment by emepyc** [comment]
tnt.tooltip v1.x.x is compatible with d3 v4. If you need to use v3 use tnt.tooltip v0.x.x

**Comment by gusevfe** [comment]
Examples in `master` load `http://d3js.org/d3.v3.min.js`. When changed to `v4`, everything seems to be ok.

**Comment by emepyc** [comment]
Thanks, I'll change the version in the examples to avoid confusion
